services:
  postgres:
    image: postgres:17-alpine
    platform: linux/amd64
    container_name: slovoslavov_postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "127.0.0.1:${DATABASE_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
